bind 127.0.0.1 -::1
protected-mode yes
port 6379
daemonize yes
supervised no
pidfile /home/deploy/apps/pigou-redis/redis.pid
logfile /home/deploy/apps/pigou-redis/redis.log
dir /home/deploy/apps/pigou-redis/data
dbfilename dump.rdb
appendonly yes
appenddirname appendonlydir
appendfsync everysec
maxmemory 128mb
maxmemory-policy noeviction
